env:
  browser: true
  es2022: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 13
plugins:
  - vue
  - '@typescript-eslint'
rules:
  'comma-dangle': [2, 'always-multiline']
  'vue/multi-word-component-names': 'off'
  'vue/max-attributes-per-line':
    - error
    - singleline: 5
      multiline:
        max: 1
        allowFirstLine: false
